export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';


export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const PASSWORD_CHANGE_START = 'PASSWORD_CHANGE_START';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_FAIL = 'PASSWORD_CHANGE_FAIL';

export const USERDATA_CHANGE_START = 'USERDATA_CHANGE_START';
export const USERDATA_CHANGE_SUCCESS = 'USERDATA_CHANGE_SUCCESS';
export const USERDATA_CHANGE_FAIL = 'USERDATA_CHANGE_FAIL';

export const GET_USERDATA_START = 'GET_USERDATA_START';
export const GET_USERDATA_SUCCESS = 'GET_USERDATA_SUCCESS';

export const AVATAR_UPLOAD_START = 'AVATAR_UPLOAD_START';
export const AVATAR_UPLOAD_SUCCESS = 'AVATAR_UPLOAD_SUCCESS';

export const LOGIN_ADMIN_START = 'LOGIN_ADMIN_START';
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';
export const LOGIN_ADMIN_FAIL = 'LOGIN_ADMIN_FAIL';

export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const UPDATE_CATEGORY_START = 'UPDATE_CATEGORY_START';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';

export const GET_SUBCATEGORIES_START = 'GET_SUBCATEGORIES_START';
export const GET_SUBCATEGORIES_SUCCESS = 'GET_SUBCATEGORIES_SUCCESS';


export const UPDATE_SUBCATEGORY_START = 'UPDATE_SUBCATEGORY_START';
export const UPDATE_SUBCATEGORY_SUCCESS = 'UPDATE_SUBCATEGORY_SUCCESS';
export const UPDATE_SUBCATEGORY_FAIL = 'UPDATE_SUBCATEGORY_FAIL';

export const GET_THEMES_START = 'GET_THEMES_START';
export const GET_THEMES_SUCCESS = 'GET_THEMES_SUCCESS';
export const GET_THEMES_FAIL = 'GET_THEMES_FAIL';

export const UPDATE_THEME_START = 'UPDATE_THEME_START';
export const UPDATE_THEME_SUCCESS = 'UPDATE_THEME_SUCCESS';
export const UPDATE_THEME_FAIL = 'UPDATE_THEME_FAIL';

export const ADD_CATEGORY_START = 'ADD_CATEGORY_START';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export const ADD_SUBCATEGORY_START = 'ADD_SUBCATEGORY_START';
export const ADD_SUBCATEGORY_SUCCESS = 'ADD_SUBCATEGORY_SUCCESS';

export const ADD_THEME_SUCCESS = 'ADD_THEME_SUCCESS';

export const RESET_THEMES = 'RESET_THEMES';

export const DELETE_THEME_START = 'DELETE_THEME_START';
export const DELETE_THEME_SUCCESS = 'DELETE_THEME_SUCCESS';

export const VERIFY_EMAIL_START = 'VERIFY_EMAIL_START';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL';

export const FORGOT_START = 'FORGOT_START';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_FAIL = 'FORGOT_FAIL';
export const RESET_FORGOT = 'RESET_FORGOT';