export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';


export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const PASSWORD_CHANGE_START = 'PASSWORD_CHANGE_START';
export const PASSWORD_CHANGE_SUCCESS = 'PASSWORD_CHANGE_SUCCESS';
export const PASSWORD_CHANGE_FAIL = 'PASSWORD_CHANGE_FAIL';

export const USERDATA_CHANGE_START = 'USERDATA_CHANGE_START';
export const USERDATA_CHANGE_SUCCESS = 'USERDATA_CHANGE_SUCCESS';
export const USERDATA_CHANGE_FAIL = 'USERDATA_CHANGE_FAIL';

export const GET_USERDATA_START = 'GET_USERDATA_START';
export const GET_USERDATA_SUCCESS = 'GET_USERDATA_SUCCESS';

export const AVATAR_UPLOAD_START = 'AVATAR_UPLOAD_START';
export const AVATAR_UPLOAD_SUCCESS = 'AVATAR_UPLOAD_SUCCESS';

export const LOGIN_ADMIN_START = 'LOGIN_ADMIN_START';
export const LOGIN_ADMIN_SUCCESS = 'LOGIN_ADMIN_SUCCESS';
export const LOGIN_ADMIN_FAIL = 'LOGIN_ADMIN_FAIL';

export const GET_CATEGORIES_START = 'GET_CATEGORIES_START';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAIL = 'GET_CATEGORIES_FAIL';

export const UPDATE_CATEGORY_START = 'UPDATE_CATEGORY_START';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAIL = 'UPDATE_CATEGORY_FAIL';

export const GET_SUBCATEGORIES_START = 'GET_SUBCATEGORIES_START';
export const GET_SUBCATEGORIES_SUCCESS = 'GET_SUBCATEGORIES_SUCCESS';


export const UPDATE_SUBCATEGORY_START = 'UPDATE_SUBCATEGORY_START';
export const UPDATE_SUBCATEGORY_SUCCESS = 'UPDATE_SUBCATEGORY_SUCCESS';
export const UPDATE_SUBCATEGORY_FAIL = 'UPDATE_SUBCATEGORY_FAIL';

export const GET_THEMES_START = 'GET_THEMES_START';
export const GET_THEMES_SUCCESS = 'GET_THEMES_SUCCESS';
export const GET_THEMES_FAIL = 'GET_THEMES_FAIL';

export const UPDATE_THEME_START = 'UPDATE_THEME_START';
export const UPDATE_THEME_SUCCESS = 'UPDATE_THEME_SUCCESS';
export const UPDATE_THEME_FAIL = 'UPDATE_THEME_FAIL';

export const ADD_CATEGORY_START = 'ADD_CATEGORY_START';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';

export const ADD_SUBCATEGORY_START = 'ADD_SUBCATEGORY_START';
export const ADD_SUBCATEGORY_SUCCESS = 'ADD_SUBCATEGORY_SUCCESS';

export const ADD_THEME_SUCCESS = 'ADD_THEME_SUCCESS';

export const RESET_THEMES = 'RESET_THEMES';
// const delete category
export const DELETE_CATEGORY_START = 'DELETE_CATEGORY_START';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
// const delete subcategory
export const DELETE_SUBCATEGORY_START = 'DELETE_SUBCATEGORY_START';
export const DELETE_SUBCATEGORY_SUCCESS = 'DELETE_SUBCATEGORY_SUCCESS';

export const DELETE_THEME_START = 'DELETE_THEME_START';
export const DELETE_THEME_SUCCESS = 'DELETE_THEME_SUCCESS';

export const VERIFY_EMAIL_START = 'VERIFY_EMAIL_START';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAIL = 'VERIFY_EMAIL_FAIL';

export const FORGOT_START = 'FORGOT_START';
export const FORGOT_SUCCESS = 'FORGOT_SUCCESS';
export const FORGOT_FAIL = 'FORGOT_FAIL';
export const RESET_FORGOT = 'RESET_FORGOT';

export const GET_COURSELIST_START = 'GET_COURSELIST_START';
export const GET_COURSELIST_SUCCESS = 'GET_COURSELIST_SUCCESS';
export const GET_COURSELIST_FAIL = 'GET_COURSELIST_FAIL';

export const GET_COURSECOVERS_START = 'GET_COURSECOVERS_START';
export const GET_COURSECOVERS_SUCCESS = 'GET_COURSECOVERS_SUCCESS';

export const ADD_COURSECOVER_START = 'ADD_COURSECOVER_START';
export const ADD_COURSECOVER_SUCCESS = 'ADD_COURSECOVER_SUCCESS';
export const ADD_COURSECOVER_FAIL = 'ADD_COURSECOVER_FAIL'

export const UPDATE_COURSECOVER_START = 'UPDATE_COURSECOVER_START';
export const UPDATE_COURSECOVER_SUCCESS = 'UPDATE_COURSECOVER_SUCCESS';
export const UPDATE_COURSECOVER_FAIL = 'UPDATE_COURSECOVER_FAIL';

export const DELETE_COURSECOVER_START = 'DELETE_COURSECOVER_START';
export const DELETE_COURSECOVER_SUCCESS = 'DELETE_COURSECOVER_SUCCESS'
export const DELETE_COURSECOVER_FAIL = 'DELETE_COURSECOVER_FAIL';

export const GET_SCHOOLCOVERS_START = 'GET_SCHOOLCOVERS_START';
export const GET_SCHOOLCOVERS_SUCCESS = 'GET_SCHOOLCOVERS_SUCCESS'

export const ADD_SCHOOLCOVER_START = 'ADD_SCHOOLCOVER_START';
export const ADD_SCHOOLCOVER_SUCCESS = 'ADD_SCHOOLCOVER_SUCCESS';
export const ADD_SCHOOLSCOVER_FAIL = 'ADD_SCHOOLSCOVER_FAIL';

export const DELETE_SCHOOLCOVER_START = 'DELETE_SCHOOLCOVER_START';
export const DELETE_SCHOOLCOVER_SUCCESS = 'DELETE_SCHOOLCOVER_SUCCESS';
export const DELETE_SCHOOLCOVER_FAIL = 'DELETE_SCHOOLCOVER_FAIL';

export const UPDATE_SCHOOLCOVER_START = 'UPDATE_SCHOOLCOVER_START';
export const UPDATE_SCHOOLCOVER_SUCCESS = 'UPDATE_SCHOOLCOVER_SUCCESS';
export const UPDATE_SCHOOLCOVER_FAIL = 'UPDATE_SCHOOLCOVER_FAIL';

export const GET_COURSE_START = 'GET_COURSE_START';
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS';

export const GET_SCHOOL_START = 'GET_SCHOOL_START';
export const GET_SCHOOL_SUCCESS = 'GET_SCHOOL_SUCCESS';

export const GET_COURSECOLLECTION_START = 'GET_COURSECOLLECTION_START';
export const GET_COURSECOLLECTION_SUCCESS = 'GET_COURSECOLLECTION_SUCCESS';
export const DELETE_COURSECOLLECTION_START = 'DELETE_COURSECOLLECTION_START';
export const DELETE_COURSECOLLECTION_SUCCESS = 'DELETE_COURSECOLLECTION_SUCCESS';

export const GET_SCHOOLCOLLECTION_START = 'GET_SCHOOLCOLLECTION_START';
export const GET_SCHOOLCOLLECTION_SUCCESS = 'GET_SCHOOLCOLLECTION_SUCCESS';
export const DELETE_SCHOOLCOLLECTION_START = 'DELETE_SCHOOLCOLLECTION_START';
export const DELETE_SCHOOLCOLLECTION_SUCCESS = 'DELETE_SCHOOLCOLLECTION_SUCCESS';